os: linux
dist: bionic
addons:
  apt:
    packages:
    - cmake
    - python
install: skip
script:
 - bash build.sh
deploy:
     provider: release
     overwrite: true
     api_key:
         secure: $GITHUB_API_KEY
     file: 
         - ./build/Ceres.js
     skip_cleanup: true
     on:
         repo: Pterodactylus/Ceres.js
         tags: true