# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Orchestrate or schedule a set of jobs

jobs:
  build:
    - bash build.sh
  test:
  deploy:

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test
      - deploy