# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Build Ceres from c++ source

on:
  push:
    branches: [ $default-branch ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download Emscripten
      run: >
        cwd=$(pwd)
        bdir=$(pwd)/build

        echo $bdir
        git clone -b "3.1.51" https://github.com/emscripten-core/emsdk.git $bdir/emsdk

#    - name: configure
#      run: ./configure
#    - name: make
#      run: make
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
